-- The planning unit: the combination of item code paths from the xbom rows
-- with scope 'imposition', in the order laid down in item_group. Usually 2-3
-- paths, 4-5 levels deep: {sheet.acm.dibond.wit.3mm, coat.gloss, cut.route}.
-- Planning tables reference imposition_group_id; the paths live only here —
-- an integer against millions of rows saves a lot of index memory. Search
-- hits this small table first, then joins the found ids against the big ones:
--   where item_code_paths ~ 'sheet.acm.dibond.*'::lquery   one path matches
--   where item_code_paths ? array['...'::lquery, ...]      any lquery matches
--   where item_code_paths = '{...}'::ltree[]               exact
create table catalog.imposition_group
(
	imposition_group_id integer generated by default as identity
		primary key,
	item_code_paths ltree[] not null
		constraint imposition_group_item_code_paths_key
			unique,
	-- the formats of the group: waste [{width, max_height, waste_factor, imposition_sqm}]
	imposition_group_json jsonb,
	-- a group nested together with another one (a variant of a material with
	-- its own paths): the queue, the plan and the schedule are the parent's
	parent_imposition_group_id integer
		references catalog.imposition_group (imposition_group_id)
);

comment on column catalog.imposition_group.parent_imposition_group_id is 'The group this one is nested with: readers take coalesce(parent_imposition_group_id, imposition_group_id) as the material of an orderline (mapping.get_production_orderline_manifest), so a variant queues, plans and schedules under its parent.';

alter table catalog.imposition_group owner to xfw3;

-- search inside the array
create index idx_catalog_imposition_group_paths_gist
	on catalog.imposition_group using gist (item_code_paths);
