-- The planning unit of a tenant: the combination of item code paths from the
-- xbom rows with scope 'imposition', in the order laid down in item_group.
-- Usually 2-3 paths, 4-5 levels deep: {sheet.acm.dibond.wit.3mm, coat.gloss,
-- cut.route}. The xbom is global, the row is per tenant: the key is
-- (tenant_id, imposition_group_id), and the same paths carry the same
-- imposition_group_id in every tenant that plans them (legacy.get_imposition_group),
-- so the id stays the material_id alias for every tenant.
-- Planning tables reference imposition_group_id; the paths live only here —
-- an integer against millions of rows saves a lot of index memory. Search
-- hits this small table first, then joins the found ids against the big ones:
--   where item_code_paths ~ 'sheet.acm.dibond.*'::lquery   one path matches
--   where item_code_paths ? array['...'::lquery, ...]      any lquery matches
--   where item_code_paths = '{...}'::ltree[]               exact
create table legacy.imposition_group
(
	tenant_id integer not null
		references site.tenant,
	imposition_group_id integer generated by default as identity,
	item_code_paths ltree[] not null,
	-- the rules of the group for this tenant (docs/plan-planning-schema.md §3):
	--   delivery_hours, min_delivery_hours   the delivery times shown on the boards
	--   unit_threshold                       orders up to this amount are one unit class
	--   waste                                the formats: [{width, max_height, waste_factor, imposition_sqm}]
	--   schedules                            per impose resource: resource_path, sort_order,
	--                                        lead_in, lead_out, intervals[{interval_start_date,
	--                                        interval_days, runs[{nest_moment_code, start_offset,
	--                                        start_offset_min, start_offset_max}]}]
	rules_json jsonb default '{}'::jsonb not null,
	-- a group nested together with another one (a variant of a material with
	-- its own paths): the queue, the plan and the schedule are the parent's
	parent_imposition_group_id integer,
	primary key (tenant_id, imposition_group_id),
	constraint imposition_group_tenant_item_code_paths_key
		unique (tenant_id, item_code_paths),
	constraint imposition_group_parent_imposition_group_id_fkey
		foreign key (tenant_id, parent_imposition_group_id)
			references legacy.imposition_group (tenant_id, imposition_group_id)
);

comment on column legacy.imposition_group.tenant_id is 'The tenant the rules are for. The paths are global; the same paths carry the same imposition_group_id in every tenant.';
comment on column legacy.imposition_group.rules_json is 'The planning rules of the group for the tenant: delivery_hours, min_delivery_hours, unit_threshold, waste[] and schedules[] (per impose resource the lead times, the intervals and the runs). Seconds from the start of the day, no unit in a key. See docs/plan-planning-schema.md §3.';
comment on column legacy.imposition_group.parent_imposition_group_id is 'The group this one is nested with: readers take coalesce(parent_imposition_group_id, imposition_group_id) as the material of an orderline (mapping.get_production_orderline_manifest), so a variant queues, plans and schedules under its parent.';

alter table legacy.imposition_group owner to xfw3;

-- search inside the array
create index idx_catalog_imposition_group_paths_gist
	on legacy.imposition_group using gist (item_code_paths);
